language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.6
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
  - php: 7.1
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_Common
  - secure: RGCqZELjklCvqfS/mMj7YAo++NBzdRUcNIv9DBTHet+05PqVdhT89B6G/OE4bxREYE1rxX4DL3CZ5eGwDwafWNAA5TQ3N8LOy4nLikKw/7SvXbiBNVBZwKAYdu43E7Vt53ze3oyKvT+B1zEFb33k2nNHJ6mIQ+Hvu04ugsKUWG3L2jHDL2TMvwFWODuKwaGbwwB8YDf49f+X2mMKM2WIfvEO2c2tUasoh+AzBgEOCTHXcbibKyk6IshrPR0DV7R+ymnOPTniv3yYKiTgcwv+nhGH7hrwVYNK8bTQjH84jzeE39bzSbPZXGq5Qy2pf543BVT3UndGiVTH7pqAYLVzWAttWFgBMVBbOojE89Znb8NBtvWCmwz0y9m+Ycm95fbTtMtwGRzzNee/jNjcG1gN6s3xf2kRIDCZBmjeKsrFX/p07UyvrtiIdA+3BGlDQuLx5kOJSJSVQCzZmGckVKGFmpcLjQG1ZiyOJKH5fiZDlsvfmZCew7zYkWlrn9TaE79WmUsrosmn7rD+aIndKV1+LlE+UadAcrM368YRNqnvzkwJ5+U/0P/KDky9ATcge321wEvYHUbgPXBLV8szLNea9w4zxVk8QKEw9awYru/3KUV5jcaGosMnjlssWEWwgVGXPiT6i/94vA39ZbSKaWtdEPyXp2fH8mbC81OGyZqtGQA=
  - secure: ZPell1PAFNa91OCIf6YoSG8lHlbIpTy4pTs86Dd2f4JMbhzERigBCCFKiK4hK3siBnE/W5A/8wHENv61e8rUZQsNyy/IV6q/VxSfHuQQLj5BiOCXiKBez3lpxoFtgSOKNynQ7T+4XNwr//PDtIz9leOrATbDypuW4qnwQCvRo7Kbk6+oeFsAEkACnBWlcadBH7bWmRChBVGfUHw7nJPIxzFucwy//pqJT1ZQRmHRJ07yeuKSiuHuh9Rq/BVW/MFV+FyLNdYWiSSJvQN5WWUA4VJW2I20KzJwZ5cOZwmen3BBOcRY4bZHivjzisElREdo++OYrHUs+FJeE5k1cnuX/TjetTAmijTVSYy+BTZ6+gJtscMJC974teolBvTH0mi7a4CCmlAd/xD+eiHJuyR5V+1q1oSqmd7OEt5O2HVBkvr6/I2ik76G1/fFVuXiNfV1RrTBcwNXKVvE8s9u9fsWp9lCFRkG+9Lm5r8mOeSr+3LkvWJW4FE2dGoayy97JFn6Gv7+gL4rg9B1ulqVLoLYeI2WYJDJ17OmgqH6I0yFL+41b2lmFmkwA37oGNq81pvNkFm63b6SlCh4eLuFa1JkK/QaDGulYsvb8kFg1pO5gG7y+b3o5uw3zKdFxDgHwTcmBwy+QaZbOw8OCBXKdq/geoylRmoEJxio0/emVG4PBfo=
  - secure: muC8DGyo52/ll6VEeMWnRoWxNdzgvop0zEtISw/gfD1xO5Bn6Heb+U1a+Vt+J9j2yA1N6kL79MAoydAbxrARgXI65/zUZEBb9XiuIKfJPzN2pXS4in0O9As5RyFkov/dduB8T4O1wsLf3p1yL7+4gxKM/WD1T5gE7VrNCiayygg0u8nhYx6hhSycIzzNGcLvM/rxLCI2YhROOHs7OFkOZQ7Z9q0T3ki7bWj3vlGJGknzVAEyA96EHxEACgsmkqrbi0qGKoqLywAI7T1jKl9KT69ukfAIzq3A6VBPgUKMSyavwILx9SLYWpGwEvTui7bYowjUA4sGc23dTymrFNFOKExL2ZDHR/LZlrXYyzKdI01Urtp/oGMME8XeR2MvccAUj5dHzBxMT1SbXGuu84oi7WXZo5Ld+OiGfJyDvs1Lxv/qVDhpt4T5A5jhf27Cs8GWLXagXdwH4tt1TkxeVoB8eFwTHwpI4KukY8z74wca5793kaNSXjQ95LkWGm+JfBStlBm4sJit6Sc2dtuqdggBACOWx6GKkaPKfKnFNvR2+pTXc1jRuj2FOfQN12/7icOjq/0ixoYadBPDnK3yXNQX/Syjo8tC24Y3vG073ztK1NjU2r7WDN8o8fnZKOLHsiubW/oOGwUzwrligYv7p9tXDqg8HpLhZnx1++4OYFkTBf0=
  - secure: FurOWu/GwxvLAjX+7a2lAstB7IuP+yCF5bmy9EmVlLHczT8V4rlQ9egFa/wM2X/1uODHDTBsawN9IicWEjOFaX9+K0Y94vjwoiOlnPpBZ+0uGDBqqR2LM0AhbY1MlA9O3T5/axXiu0RGdc3hrRXQvNH9hINcHFPh6gFpdQuJcEtM97lcHu/wPAJJyLC/QZN/4s38MP8qspSFxCS/mM7TW/ZiplcV+Xxa0bf1Cu6bxFdlBG2wsnDQvwGgVWhCFtZa09ym6in+WuvuXn/qP9CWbhhSVrFk/B3S5sesRaM2xQjHHPBk8MiuPkW4vDil3XlFr3Ie4u5YLJvFd7NkutgMuBhjWn+XAHFArQW+6L23SaC2qVa+TZ9SQ6SVtKUije2Zxzw2R7akU10EIvV02bvz7VyllyNcymHJvpoJigL63hTScF0lLfyybZlkv2O/yK/0PnyTZqQed7wpZlJ/ViPfjW9dA7+C1OyTkAgulhBceApyEwGOsCplenVCIhOkr8XS++tejcckGToO3Zg/xmQduBCkD8nnfc/5nYF8BOLc9So5B4giESdvd8FJ3sOrHZES9SLqFu44jBleXkMb1meNNACvIAtg1w8nAYY/taN78K7Bld+tumzdKrWnxun//w+vHfFa1bviTAni/pav0Grsl/MbksCdfMw83uRMevYrrmI=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.7
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: VJbbEx/ztG5F5+xIpjDmhwwFEFXgcly8iQEwJguwQT4N3JoID9LwGW0/VY/tvP+c9x5drl+EfpC9a9shHHVsTEUXHQJS1BxhLB8zrqbe8Xh1szqIQD7kfCU7wMo5oHwZKKpRbJyAMi2Y8eZQZkbCYy82blYia8P8hIgH9Za4c4nibdiONcmOaG2MsORJu+CKSJWijZsSokNLypTGg+ZyrkOB9H8JT4doJ/X6E2I8Wnv+kz7n47Szbita+MUeJHvfnWNPnXfpxV/EMpsJX0cLBDCJ4eD23+O2SG40sZ6JjJMJesMXuyipJiLBO0uBcF3iP/9/gqDYlbaNiXzuTKkrcQ+MgzQmGmpR1Mno6LiEUmEz9LurtRj8GZz+9J624uvIyl/OMGeA1z6o5dIpP/iI0+/YETU0tBy3WyI0Sri5sslNTBE1eVC7fBu7tgNVSLPwqs7kSXjOBrQzmYrzbYl/jw9qSp5gyRn3bBk8tgyT71/rE09/FxP04XGoXZeRUoM1RgsgBOd+e1ZNH3BNPmiZb5J5JShZmKLycTmYW1s+3YGUKO4ecDtstv4n7kuXFbZ0WpcTIs2P+r4dIBehMJs+MLHxM7TCsVDP3T+c+WLdWDerEl7jLZCvchL9CEQVgZZnODSPbSjLq6cvPcQLe3AbQx6WdU+FL05LQ/g4f0XmgK8=
notifications:
  slack:
    secure: MVCoKIzP8xEY/HShb0f/Q89ffYPN8fpUenNUf2fQu8FBZRUvjZA8TEn/4JZl+awbNkorPc3xb1sqgxC8RFunu1Ttq7GefajZ2An5ZjbijdzTQXGg+RZNmCpvRKMjGFAoNI9oIw8mekE8VqHOQ2dKnyRMiaC3aT4yqRwqQoO2Iuy27JNlXf35mulkAe3ap+A6eb41eSemkEBUCuiS+tP9G+mkit0ZVnHpiqM3VuDAYRQ3fuiOqR0PuodDkm2j/dmNuk2ORul7lgmvBAcbDgz6iam73XQKW2pUDiDWjXgy+uKJ0ebiFG344GS9jVkm5K3+zD1w4P51Fs4RFtiUPHhmmFXZ8Gcjr/UsHqj2WBn8UP3E3ueHh2EbOJhUskut1Uq3yPIi+jlp/1mOLW/5D3PCNp7lBae7Mvs8WCqshdoS/iMMdHogxgC2HhsVqeMhN6g3Dk6vupLFLCnf2YpgKqMYvD07zJ+lRr3DahatDV19l1R1MFvp+gwgGelV067zKWo3LeOH6X5I565eC23t/4b68b5zEmKm/EzdSSWNi36qRWXH8K157dIK4zx5Q6n37Pu7+hSBsMZLj5fMa7bRf05EVH/vUgnpQADNDWx8qoss+eHMo4ccKLktOUBZpH6M0nucW43M1FOBeWAj05NdFJl3IURZNBww/qxUpmDbzGGXL/Q=
