language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.1
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_Common
  - secure: Z0zvf5tJJ28hNTSDsiPwQmL1NeVhAzi7J+4RGQVI1k6XQyeRFxdVF7z2p1MR0RUs8e2hMqqJ9227XetVABaYRuAowEMaVjptQ79nbb+XLTXULPP5T4xtAmikQlBSA9OfPXEnmcEVCg0yR2XFanH8MSm3LhIBPYmr/MPJeWR9L+J0hRctMDG34GxK5x+BNk3ECQ6Jv/PRgay2b55VmjBJ7DcLEXNio7ayeoaUuxNx5vu6hPuKnzAfxscVJSYg0o6UvQkw/n5EZYLAAcDx4zWhWH6QxnkYO/ZViGmZCht1RlTYEYEin+VclMyQPUx3gIySDKg7eUdXYYbXwNJZnUwkf1wKu1zRJNh0HUbZCMsq1XPhv1y2pT3R6qQJu8N34S12KgBFyiTgt7rhKo6UuAUcnBR5fK4oC1VAfdr6Vf7hF0QQsIRZ3UpFEtvaFYhjR6FCB82iZR8GitTBVMR4ojFNf8N7JS7m5JLTZl3fsf8LaKuL8rG+Xqmytc0t0GBefvqVGLItxcnFKou/vs6ItxYixdFwtals5J0nDIWsCixmASfW5Ga/Ow2wPYmWqM7CHwrg4vf9cTBkfRv9AW7bZZk2ifAk7A/owehatG58INKfR/YpsZ+U4EN8W6vlUl/7MY8pidoUx1IBbsq4Njpe88VA6PFrfF4vyPIXWir9lIY1Gyk=
  - secure: CylhZMVeatDuq3kswe2NisunG9lhaty/3OxNfMhKaz1nJS+qENGBDeIRJu3s5lavqh5/v/MwGtc0gZImCbEZ65ZgWNWZxQGTSGnpDUzDC+e6bcVlkqsfYsuX+hQzrY4XdkvxgDiwgXU6rzohcAjZEl5NsRsAdkk7qbKtOxd9yllbBoQR8S/l/N/KyqSsqTYtwihAZw+kiZENhSl3DeKJJY3gL6Hpskj+BSam1ANcoqR4qkf9jCwZyn+GqO+yLahLPq4LwwX/7Fkg7PCZMLv0QvVDEbcOzAg+7GQzt3oy8m+G25rkFII3ONGl/jwFWROISIQTgY3yXieY+40AelzmU4ppEn96rftQyYH55BLeWAZ0PIH/BMnHQIpEOKg+p1vBc8e2Mjbu2ipINF+o3OX1vg0FBa0epmAhnzgaiw8V7Xq7zNJWBtQDg0XYAIN3q47zqyGqLfNN7qZUYifA2SQ9ahF1atgv1bukQo8qG/iaKNChYgg/ZZoQn3hqfWMMBwGM4e0Yt/YI3z0bWt0LbI0hr/4hS/1Bhtn9SFUMAzE7p7VTG4Ek9A1U26TA5Kz5AqdB+lfH78R/CbfYZpmNGLSoNF6WPSGmGbg+n0S1frNLU/tZlp+tBwEwnZFQQ2iqb8xl1XVBYGS8let1jmt3pKklk4EPQNRUOnlQPmr0zeM3B2I=
  - secure: XBRiFZ3hqIr7lA1sjsVSnqzEI89Ld1VlKYgwsmCbXDbxKsZ5+H64WDVzfB5Lp4R/C8OGb2r4c4isqsZ2Ju2SSg8pZ4zvJ25m8XCQSgNVTXqRKPL9RSbPRe8jA0wVIx4EmATl9BsKhKggMklkyNNWy7IkCFwR0jfjDX5mVLw/hVdPFhOEOZ+RX+7ICroiZsn1hyF1cOG4MVCMMydy2ookNmp7q6WonpcBbaGbsh9p6fNK7Hg6HxQD1cvjkVphidO/9QZKSRPo1/CNQ/futgohHQT13wmJfCekDQX9GRPnGeL4EGmJ/y+5ueDuXXf6xDZGqGs5g6NttsFksrNypPA9pJyyPR62S5xzUbBWdPCz9Ues6lIl1JaLin+xXLjBkp6B78qciMq40so4HWxtrZZqHNPBv2b4WZ65xP7z8VnRt5cj32Z27x3QOPdw2H5rvDHfGFt5IQ463migYN/xsEVp8gPjG/ltI2ICdkHOlOOQ3LumvP0JFXrRLU8tCzNecfeewNC0AAVMoti/j5SbedN2izkd9Ovi17C2F+XqrE9ugsaMQhEYei2sL34Ngj/sA2DP7VWeB6jFObyfOOEEJRX+VL/fvFBayFD/+UvwM1/TaM4Dq4pjp08p87EPZrr1Zi/8vQWj001Rut+4dFirKbL0IahyBQ8aX7UaZ2Fb3+ZPbaA=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.7
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: Hm9z9cIMBpD2cl5dqfcgYRXuaL11qfiQi6j0nfb4pLQlLrpnIBqZJ+0VZ157RpKuMwdQL3T1TBCYRwanI3cI3v8dKr1uW/c71i82+NSeaqLQIL0NifRBxHgxDbieBkpirL3RC5faKx7zuIjFRDHHXkgH7JFcDkLoXn40xKNwpTAOW8uwXM0mH+IYX7378RkpkroaKMV/j5dN4fj16jv2fRso5FraT3wHxueDpVykYmHlhDGtiiCXjUShuGRqHkbRSfkhTkpHiLtHOMhfMsC6u308t6RxcsMByDTfit+WSI64SOC3HHIy7nlIPGofOl2eGIo/UJz6UjuoyzWIJ9d6ffqUkt/IkqlMwDJZbzYh1Ik1P+DJ2E07wKu5gWOuVv1RBvsqFMIPaW3GgPVJ9kwCFPDC4FAX8D+H/Z7CepuM4qFjol9HbP3xlbNr24DJYI1/UyneYoXyPG9L3FHM0Bb9VURVlRmwPUKmk58MEERSBnNhLElP0rBpG07uMxBnKRF/V2lZYI+mSdhDw4Ha7fQiEyfO3ufb8gess8HEKW/a3Q76XIMUGexffx3UzqeJsa7D4Q/jF4lU6d2VvWs74IDCK7FF0wQzjMEqLLOpogTzBbNWr+lQEuc1CExscJ4szPzlZLvLVgoY6pFro03VyKaOMFsQqr7B0zbhdc7HjQHTSX4=
notifications:
  slack:
    secure: NM5ywux0fH2HnQ6Wn52MHKixdcSU70vBaEhCRFvJcfwkz5yYqZ5l0n3bjXAlMzS/s6te3CYf65oyF4rnA/ePke306uvM6p5SDxZeoI5VsYkBBHRzUwLWL1p6jDc+DMNUAhttY4Vx+EtMNSOb6uZegel+6f/wM8XpphlTmSOuBVMnCOV1CoXPJfAqwhvHqzsvSqL1oekcom3XpHe5m7TWLHcGVMdm2A8FodSdKLSgerL4AhR0jlq0QWaAnYf93u3MLkiQ3ey/eUGO0gwtW7u909n+tvlUZfTWfgQpj12YyEIWm4qTTUJYF3Gn26cHEJxBWT1Q7su+5GzW0XL5iBG7Mja7+ZbgTOuAir4mBf5RLvkKutmZlzBtxJEd72VSLkK4l9YFPNTPJRANDrWJypfSgTAVeLnTxFBiNWWzsPfCGu4XX9RLf1lTKivJ5dW4GYntz0rnpsnrPoWBo0BbYMh7lvCaGF6NbGGv4Ot7HnLJhcP0auIJeP0N0Yv/M12d0XwhLvtjo7ucg+2U1+1HI2HnWS3ic5IcHHejypuTN/OxkzzmG59HnLsezulfolGC9CY5/zvyvZ9o4rXSqJnHh+9TO8EAfAEuRehJWXsfljVPuSCrwMZHWDzXGDnlNtgURmrZYJcIgeZvCReEpYMb3uFqVg8msakH9FX6TyZLs/QffGE=
