language: php
sudo: false
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - env: MAGENTO_VERSION=magento-ce-1.9.1.1
  - php: 5.6
    env: MAGENTO_VERSION=magento-ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=magento-ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_Common
  - secure: VlmpwI7gZGyQ3N5d3FfyEIFX9kHURW9b+jcyK9sVJVR7jiX7Y3C1XSz/692eAeQY+w6bohd+6kaWaVFb46NMz796YHI9iS044/b6RHsy40GYi+c535FIJP+s/pW4Vyp3m71kIDfTL5uuVVwF62QFdr/BLTuzlITFDGzuKu496oST/0PFtbp+gps20lAkiapVYASDE5aRsqyMJLPVddcA5hYE7N3zketAW0czwMSlhyNYNbz/9PRSaVJLEodaautwfo1gS8Y/918gvI7ed5FSZARo3+B6k6fa5nRWnKDwMaeW7bcosC67GtuYAA00LwFn7Vy871ADTYCXs6lcZcKA21wyTsZ9/3BojUv9LPPa1Cp6QYNo9+5ZsjKrhh655AxJzzZz6zyt/7PRqhIQzvxaB4MGK+QWOoDOjQiu4SKsEEMMs7lIOUrsK7h5BaWLDdh1OmIOWDb7BJ4rfPtceCSUV36Ac07ANEWulxUOn+NCCUf5osso8MVCVNeDei1cZQCjMAoNp9o55yMiA5bVfWaBNoK3YzYCQOrKoN6+8dU0aPLhY71BwRKWNQ8OOronSoIikeV/4Dom3R74BE+3BYQciL8nvlE7kt5ucQTdRaxxkoS8J/Y7xaOVy0s/LS7XlR6H6ylgG3x3pdRTHkU70/MMi4gxNWR4TKYonv3PRaFXyq0=
  - secure: XNwFIPehHCcYgtZWOhTxZ0D17tFhFH0jn1b367zQwiz0yz0SKDdBxI7aH3Kp1T1gjqgS27PxCQnVDVbwgcDb5JbZuKyWkSn3HVVaJD3YJhtifCuBdc1Cew+uXfwXlZst3DgGxnr7eZsMgEBRvANarBS7PQP4Hb2XmtpoKBlOTG4jN3/GuTlP0q8XRE0gWhcY9c02h7wABBVCD/zbte5ld1rDl1Qaxpvai6Pq/ETnwWeWP+2H7ynP1jldSinBRmcjVMjhnq54gKdTnGKeBY5PTQIjJrcJFjdKNhdKxUqSZGbNCDg8s1Stm18tD4o3lwH4ebjhbkarJCc6gqAeVj8sLj36O3l4rY5B72pH91vJgxUWv9P5g45d4wz/98k3p7XIvUIg9ZJ/mDArqA/JcfQkqvIL1HqPtL1nKcviNId9YMw6nKxzBsv2EV6hf6Gtkchlou29Qi3ytB1Uw5lqVgBsFl0DYTq+rgyUVgtu+hRu57iLgvwKfKfIONNl+2JocL7AWpRdnhsjeq5rm7jlQ6yuFNcQZA/QEwmg7mL+zY8dwtBcv9uQTZaTjseG8soObWkEzk+HrhTEDQMuSZSE2tiZT4wT2doeqAX24fbSv61zaT6LAZDvXZCajVnTyU1s3l58usc1Y+uZxC2UvjcWnvfTZ4N51LBU8t7xJOLagKBqkJ4=
  - secure: ninxwtnpoD+ioc8Uli9Vv9llMbd9mUyM9Cz4ILSmfOfq4tjydzn029jyHdgGp+C/rqqBKrhHnNo+fdSG6PI2SSA1OLnu2WNtS9+ndHmFxa/nzWX0il7mzwAd/NLWOkvuu2iMuTyfiGU3ADaNJAt6IsqrCN6NlSYgf2lmnp6+BQXAFNeep6UfYySbDi6ZMfPvP6sNWBwkmxJIf9dWTEE1GDUoKiUd7AO5D6SSVuRWHuC5OrSH9afrXEMK+QA9DYPJt8xdzsATNiKTD8T5uDO9gtiHQ+xQXE7hl26SaGwRo7J+W1G7P2h0etgLA8Fl3G3ivr5kplUfooqdEGnf9HGkyAAl6IS1uHfDs6RwWewo00wlII4Vr9H0c83JzyKvOvdQ04DBWRQQe58VxuT5UnYGk6pC1GaGkVAWx0Na2culk3uXvzGc9JqpTXXK4NnwpyeWqMd+R7YwLmYZn4Qj5PZEAf8Cqgah/HMTmi7xQ5rb1Wgrn3O60efgJs9v/uB2Wr2ed+NBlabdjGvX8RxAW45uorxtpVV5rygNsYjzYkxPL5KGeHzBzrFfF0BcCZkCNrl1ngOMYdBflKM26Kgx8Spf3rbZtlsLizsLfM++uQx1R5Q4FdTQ5l2dZMxSl14DH7ChmCSsSKsCt+HSLPafcVheYvbhXZ3v11Ml09YRJc1e08Y=
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.4
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
  - MAGENTO_VERSION=magento-ce-1.6.2.0
before_script:
- echo > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
- echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- phpenv rehash;
- composer self-update
- composer config github-oauth.github.com "$GITHUB_TOKEN"
- composer install --no-interaction --prefer-dist
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: iY3WNEOjxHfpKywlESBuRdgOHf1rdvT0FQrFenH/fFKNnlAgO1n78/00nfQ0h7an7QYnRY8TkaCPDcOXoRNaEJ+F1pvPOTflTXOhE8Ftm9W43s4X0guLUfWSc0uHBztEFHdUMNJulH8aQV0wJc7uxGE8e/6ZVafCxA9tnbyqlzLx3hxHlrjwSafjSMyvXT9XH8He2q2vfx6nrq9y+uO4OBl7x8K8vxpnmCGIXYNZkIA95DUUYrKUolphEQiSi9RyZcBkNAXNkOuuTQ15e5ySz/ZWYI0vS1ssg+vEktRdAJC/XwSFscTzCMUSbAPAKRBX/0hBzJ7iYAYXF4rKdPfdjdHsdBpI3JABCoUW17N8zgn/UIxXmkOQuNfWjOo1Y+dYDv7wiPMViz4eNspPHT6PL6uReC4/Nr5VAyQQAiaBHTDuW0FAcT5wlbTY1Tf3/V+SM3OiHUmMA+BZqBomKE10hbBrvSdFNDTWASBKnSOiaufU/85Ou7NSNFQwt9zK00spdyVFCEQ81Fxiv8UOhBnB5PRsIuQgtAaPRLhnUZtVSWTF5dOwonKf4W9rXPzc+l9XC+fi8hNj9G/JaacYurBoUsWFAklMOEwDW7dEeJL6p2yzVRjUPtx1xsLYcuqTn43xk1H+JAVPawSeNPFlgjHQ3Vrov56JAI+J4MEO1Ny3Fo0=
notifications:
  slack:
    secure: FUTMYx9udYDxI6hzbWcsTdk6nncKFvf4nUynJQtro83L4gvTmvCuZokZyfnv59Gzl49n0uRvdTAS+5Wq8vmgbnftEuwunlbT+8k+BHxZuHr5ciqUqa8n1DVtoxxObsE8eZq6VIrVD3qj7qGLGMTgTd0yWLLQ8EwqjrXTpOEmIPPsg9uw2ndw7bLFrmjB5K4kO+VBz97qOVOyPKAzmlvGLPgj9PpK/hz+hKdLjmjexOAFWh3687Ed1hJHsYhRgnBpynBb0xFmJRxu+N3g10OI0RII/5r42a4jITC7x/p1RqcDBwjMhfIhALdAyhc5X/jk7IGiqgoS0+48a2pkcLAoKHVYkekM5ab3TjTRjfWdlmg5PFkWyMhi0d0E/yc+eE6W7Uzt8IGWYiI5Xx9UVl4fTUs87s0C/yy7KsS+jD45sqRT1Q0Cd8e//nACeBRSimxoSG5WEXhwWcjVya69Cirfurr/XzLUL6WAvS4ctL/At6JYZGwJ3OslexaLYERm4SI+Cf7gDq85R6pF/OOnHXEpWxxweeqnBi5i2MSvFvCtOyyKXtLmQSFj0YO1WDXgVdSApPDYS+y+Aouh55worOAIr09yc3OX5PnFXNtrN3nkRfoNgf0ILD9vO41eMkHVjiTGXAyHiFetVqn/s+kNHymvzRJBWvY2A+132oZQnVVGVyg=
