language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_Common
  - secure: GCk/JGsj1AgQBRJIZNdJrbqG/Gkeu1oYIecyDCASlIdU9P2VzPbBdZ06OKzVi9kiYP+IENt5aK6zo294czEERUgbXCpMgncM2D2ZE5uoJcdFwx+eWkJBV2KvNcGQfCRvYm81eI1jri/vsRdy5wyrCndMw79YtSOhP8RN7jzxEI5qpwljzWolXV6N6EW1KaCErn9GG/H2QO7qJaMo8/4DmLK1PoYx0Y+2dC93dGF/pgpk5kl1Q2CG5mvfxrXfZ01ZLqNwRk3fe5j6O91epAPrM2jma6cog5MH3HWYors4Ajyk7/YsfC5AR8WGcW4sLfJqGNSkzlp0qdyz4Wj9am6qq8jwDD/11UhUaLcMbzOzBE9wneU8F29fLAOEPewlm4gMeuIm9E+tleXECqTzoK7TH/GPDvTFlsYuV0+FQWVlESfHi4EkZzp/AiNvhCCtqgKNlEYFEaUDYg/88WbyWuPQEm8vtWkrzpFdvBPYOb3g9Au1DOYuK0sApJyGAtDzEkM/P1wGuXc61kUoEqQ8O1el6LwiNmOJGPO5rY6toDV2LwVOvLkRW3ADtDo1F61KjZDfH3JzBMvj0F2olZgGjx6Z1oGUsOLA8auNTjDdq0JRLq/EolyaHheYKpGyc9E5BEL1JJWymcFNx8Cgb6qVIup/6UCn10ZyJJihyqIo9/C6kFk=
  - secure: EJs+8o8cY7ykkYveV2UWSxgPemNryoQiKCdxR0wzj2VNbAzo3dBt8ltl0KnpTUx1cb8ItyvrNxAAdLAuE7E+skZxIrZnmqXJUPS94EnswfPh1gXpw5Ma/Vr9tPEIriAZNCvX4dDnb+NcuoygPMPdEz/eI6fkV2RGzJgEO4T3vUiTlhHarH+CNbT50B1aObEjZUVflOZN8MD8WK1MQX33WYQ0KnUB3avwoKwm0mIpemaF+qCPfYVK3IgDh61sHtCWkWNMrE7Lrtw7c7CzjikW5ovpVrYTmAsQBsoK+ndFBCvvqYuGaYSGlMRxKaFqlJstcQWZb4/KiXh7wKHMtqZmUCePuqf6BA9N4mgA4C6kOu+a0Qz/0nRKM2Z/RbRijjgmbfhTlUL0aMLAH5XCpFfq4jkErw9W9dZoitqYLBxImMNxaKnu9lt2YPUrGiCrknfrFuce+nW6luLU34Xy3VzH2M1yyeu0LJPADbqifKDHsHNAGr+U4JleInSlxkKTcj2IwdRUOV42AU+IFzg8hMrBPjxie9FW680I3T8u15OuEclB3wzAjaUvohBegbFB03hxJymd+Y2rfmH9IxhA/FL0E+ZSdL3G5y7aYx9FFucl0ai3zWxNHCNydXMYdnKTL0hMEYwCkZvJea3ZvsgdYcF/umJNtkDIxXTued1TL/8MdD0=
  - secure: meSviferus6RXOURqJgRXS6TSaAXQaHNezIIFT8YmENc+5e2AqMQj65QLk78iU9Po/4as2yQu0Vx/0HGB79jKNyfa5QhVZYvsLf+cLZVdf1Yk9Gw9ys9TKm8ezCYlXGEhueRdHiUMA1pVLKysgrPPjL5g2PCblU5qOnaILAf9iEpkedmkRJRV5ilXwCh5TYV5FE6DTnHvBnB0/JdlX7HrWr1OMVsp9WPkfEar/xOZX2szH8CYOq1/xvyi2kfYUed8FWjTA7RBORAomFd//jGoPvw2xItEfu12GfKfINXtkYjYFMzKwVLBeXcE4hEgca2rfeYrAqVk/eR1F8RMgp745kwEQraAPx/nNMn6Aa0ts9mEwRNGvnKLJOmenzMlIKBQZ7Ja/CAKndCOhNaOcmsqXNvdamfwa1satwR+W4J+LE7R1Q1I/Qx0gqfYOCnrWD1pUlXI1Q6aUi7Sm4Cy+nc1Lor8J0qY2Psu/q0h6LhrU78sUIc8C4QHbhfqX8COo23JzbKPI/RAwiFQ6flsXbT9Ed2uWaOpbNUoc0U7OH2AECNFrQ9zD3bsda6FX87qGGSwYmTRGLPpuCQo+/qrQrdYEOJSkydn9kkJOpyfXnwBypYNUoOmDPeS8npCTojFvOshCcEb3tEASIRH7MWLo3Dwea/j80FYw40hCPJsAtb7O0=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: pf1qlMRQ8OyhiXkIJjRiMXPMZ0iDong6kFjn/6hXR+lximSoopNuYVcaTlro1dUb3EDIFFQtkVem3AewK06ctHiXr/Da09dqhKvJjzRdx/iqtqTsq6g4CYwRiMOuBW+XlmQN09ZqAnKWf2v2Om/pBTJzSU576w6LT+ZGrIbplfxZsQ2kfkY1jq7faYZwvauYk9wMLTGetooIc/tUTHQDfei36eHKs5K2ymA3nRolixIEZK1o5ckFiAYPnBoDDbQX+9VmV4LOV6w5RhlEuG2fqKsBcmGT5TBVO4oaS+lJc/qmqQ+8zgmODB+eynhyRhkPsUg1csFjjW8yvaJhkTS3AKk3H2RmbZTkXZHKGrbEYSkwGLpIm1iOFstLpW1Lj88ti1ClBfbNyZkKcxmL+bgwC/I8e2MR8/jG+nBMTOrlpdDVC2VdyR8zPdlRqiV4wsFCX9gRAvkxRL8Mr9cIUyZLYfnREHHIsfMpUCjgSpg7MQ1TnlUpc1BAshoJjLxlF9KZwF87rBPabk507w+a5MxkQTD9CENk92ILMa9QOYRXy+OCEDEECU8lTham2RT6hkjzEAoN4THjTZerlbnN4LiId30SraWQ3v1og0Z7lICx7wLQvn+3QeOq3r799zzDoaG5b3T2UALBC2qGpeo1KKBEWiA7dze5fOQGbfLRZ1zgx+Q=
notifications:
  slack:
    secure: Igx8IOFQnhQbi07/n63EZrknt0n6AB/hSBGrKyjtai1GqfblgUGcy+h3KKSPR2h3Er45cqpVknMm3/OJLG8CpdHOWtEC53GcLMg1XCpH/Y7mM3DcX2NODRgdiNoDXUcS63vCNxbpcrg6iiMTaYjHJGWCDmqjHOs3ta941rSSnTKbVjfzrV3zJ7pxN7BzHpScb6Hlehf/2dWUgCskVuqW7Nr1shw9uqPkjyfMxHrm13TtUnFQt1neP/VqNG7xvg5CXWSiJnl+2ekH6RZcPtHB5OKsYB2y96U3PEtHvcyvfgZ4Yf9SMaRoEHkv7yBAmfNt5baaDKxS+kG6yOczmUtv3DusUPmLzdw+qXznMEsKG5gOKCOIQHUJKl90iljHUe3z6dTkrl7xlsFzhB5neTfIYdoybnNVIuvQE8EEGb9+NVauBLzf1CNvPHTeooeo06Bbb82CI3cF1j6kk3APSIW/6hLww0DSwMRWeFInjGaOxbptDcOpi5pKiQ2FiIxpjlLUbdXPbjAXYpEzlxNblHUlTNzweyq6NvQIX+AKMKrkWUgq+jN1pfQxszyH4j/N1Byst9HJhdu8NM2Q4tIi/pvwvHO/AiW6vjwIlVAsKeOKRQKAoE5YaABiZ672y2IVyKpNYOSfjbLCUhePOjsz1LuZr6baQAH4/yxGM2bgWCbuQsA=
