language: php
sudo: false
php:
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - env: MAGENTO_VERSION=magento-ce-1.9.1.1
  - php: 5.6
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_Common
  - secure: B2Oj6DB2pSpzHmisLomwq/CywgIm2fnIJXoXZLh3+SJ8LjswFUJX5OVZTUbkfYV8whI/aUleq69IJPk1RboHCYp8H0XoMySiGew+N9AotkxoAVq3S0XoiCqf3R0lMjoMFfcrMU6CbYCY4+yfuIjGs3LTSbbKv0ag5DvQX8FaZ5NQbuchuTp5mZpntqt0TKb47qBkoCSLk1z4qs+CGSQXOS4rPgzhzlHrClTc41ITwaZi9z37YLAum+hFH2La47drPC9gMZ5pJsLDVZ4VU82sAiN+IEf82VrrqvACtNGP+r4bQWxQ83WPBPoaN0jlmIEsWwNqlgqmGejSHKuFbCNzcaHE3LdvUGiIO4MwEVUE19xpDH5ewDL6EWaC86WtjIvT46yLDtql2X6R8a/vgz23e8rt17E+iO0sGCfyrLpXE6TErDgEBAoL1BWVbFDrLkVYxjs4/G9gT7kGPq3XxQvV54JBXcFJ5PEAvux9cllvZt1PjgG+M+gc5g5rGC7n5nmWjgK9nR/R2JXNnFkTac/G7xpnPVK9vwbKLuYIBl23akk4IXuuKfcEOdi59L1sxXEEMOQLFMWQBvxYhQJHSld8nbNEMvAtBNJkdcZoDBMjAalIBYSvT3n6aq2A8c+alJLiTuUV1A5iQPohXyXbiNlQjjHjXOK+WmpkSxdobi+DHSA=
  - secure: or+Ilp/U1CyVsKy+SWQr2iP5oo1aYzYrr5cAo1KCIgohhCWhPNDU+y07xeWHvEoVsahjk3zkvB/rLIvUmbsONEOSrAeGCKAw5iyVtPOheDyE+ccxv3BpRGWRePygb/phui4EVVAJTzaKwSvC97dNxmlxD5D31KHVvlOG60yKuBW32aptjFXefHZViMXo2bsa95WCp9LMH1hAarVBM/k4ySlPjvNNia9rNoYu23rLzk8qvKjn9nAmcne1hjMPJV6LiYpVlcjM6FuWVxkpWxIrcQBcCVEgY/O46GdxJinrXM8t4RUi+dN2fM9HO24yAQTBE2M7fRmshtIZkuyj/w6ehoz6jUZcy5PK9/qrPp076uyY6aF8R/yGntpoUQgCT70uCac5mOcIUM1rkrRoZVph/cN0N88SliutOMpPx3ZXYAIlGpNZDwjVykGvMdkM4A/jIHP7u/PPFuvwIUuS9Li0bkbANAfbRN+AGsWgt/n3z+1QESce1cohee8IzF+pU1CwoRKVI9z5pIeYfMrUAMlP9s5pyYSwmgYJI2mWjH+NoUxkm1FfUKlsDwpPyiR41zkRabAlweHd4TYYqTIDCNN72Bdg1ep9J6SVkEGDuvv8Qy8IqaUeWss3O3azXSuCCU2XpceiymeUZcX2qGBmU2AR2LjlmB5+4pPfOeFpfImHBGM=
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
before_script:
- composer self-update
- composer install --prefer-source
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: OzvUikrrZFGBpRgCNLp9kxLLObe6/0h3//lxrCr9b/m3YjYjOO8YcxizutZS93C4O88w9gFbajcyn1MgQP10QgcsLXgorgLOItj9rG53ORTmRJuvpqcU5lP0xOh9Xw9G+xRAfS8RgO2ooi97/EWg3gQP4CnccdK2l7SAx22+e2omGtAAYdk+naxdGNsHd7OpF7zuc1DTCq9nHffkfmETP2OhT1hBCUg1MPvEu1/5R16fw8yV28w2KOlgqOnFWL4Fu7sjNO/HpRJUND+MUAGqjKf+H6l4iag2l4ZYJUx7mPmMeV3pqsKV3/+ehjLBBO60mYR8deB+iD/MyRQL2rJ9CwoT65kmTQ4kvlfjOjfh4ZyppTqCRferyUvrPF939pgSidqYRBCqEuYxJAbM+YCZwBIfRwe86mAAVYv7Xa2ItPACl/+qsgiXCMDan+/IkxcWFGpeO0I7K3Te1QeY7/Shj4WrN/9MvW/PJhKTrYf2eiKllOBzDio8r9JrhsFXcpKGozj1i8XJmUk+trSVA02jIRIx2/j/LcopZcEsoQb7W+FACg3GAX700Qym8adhenP5c+/U3QJabPfjkWtGFCxT/90FbcysB0g69AtssccGLGAUjRWyNy315EVtL4geVJndO0qvM8hSjg7NsaDLD3z9PoQDsquVkJnqYO329K1HiCQ=
notifications:
  slack:
    secure: FHp8MEC6g7vrQzNtb7jXXrqSgUGS+xf/ySv1dww34FHMuPGfInisBcn/IsdQJYulMqSYCIfB+jYIjjCWtOV+X+kKr+9rlL4mnJ29Io7sm6xVB28CHoaVCja0wZ6EObhZNEbleD7cAMjvlNjFRkfraJ6RHrlfGvRxVlb9Y9UIc2Pqm0+x2T+s+xMeEqL143g1DmhU9TNTARPoFEgXchDCVq0yqcG8dIVBoAMWrlZYA7xDRaKuEAY/OAwfZwdIBndngipyCTkxrxKfrgtLmNra6Y/R9AfUGvjB5r0M781IO9oA0FQwzs93RZ3UgG9Q7EK4f6ODh7QuSkDpjavZ4yPCTWewkRZ+57CaGLFZzKWmjBYdu5VdzCbgo6AlcxQo0ANN5SbDXHgraDkI+BLUj13Z/kkLpW6e6PmDXrWQkH29vPquNNNZSsI1RKaCkhUwDaneTWXo8czgtiWOUIyv0HHJZNnW9gP9cOS+rL47rx0Ve4rBmd+ae2TplB37UQ8ovsT86i/lN53jvD756nVBw54uTq5JiRMe2m9wdGVnfa/RlcSHJW9gJ+9D2e4um/vUrr29510bWoL7HJLXcKcn51M7ZfiOKMRioBvB9CqacWjUJyLqG3EW/7WD/ItkBaZGTLYZCb6AMZR53nhTTZrrdodFBTiE/DmOppT6Y5oFmlF3/Vw=
