language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_Common
  - secure: FuGOU7M8k678RHLiyycD91A3vho+3cFMRslQ0ALoiQTtEyqoHW75saF+zZGPDKj0dFo90q98FT6c5+Tww2r9bKkpacgfkOKLrzXr5K3zgepPZlvpQl8EVKIuJ8lvppCMa6cZOfu4FT0t1ypqe4r4QgeEs3uI5+7CjFecW8z+c1jjnZKMYVVoflECtwrEXOVymdV61OJJP8FTlv23NKFljSe9Hcj9p1hcsa0ALvOpvTVzkBXpxMucIsDFVM/fbSOujTy+XW+rQOobgHIxrcgQRtPMEeLaPPC3KAOWuUue84KghHSaZii9A29BkbG2esYp63CQ1vHVxGbxT3q3r3va6t7+cy8GmBFIaAu38i36WWq1MR5hMBeuiHDMy9RtnNpcOTJeKUjoSl8mJXwaOz5F9qb9rZVahx3Ydf2aFXjp0K4LZW1/eTMaxW26ZMioTqXIbDxQz29f4aQDGvCOm957jCspWvraN5sG1ue9GMZ4QTJ9DHnA8FHiCDiYjVBX/3XNNe856aaV2TsUnBEng5icsr3yitvYmJVkvjvt0bClVz495VlSnkyCf2vyApcgktn02EExcvEatA+ICRjQovxVPUeMq+8YgD833/JIinFHqdvYdorOwLKWz3a1eqYr8O9QeWWtDTImmCkpmDY26ervgGoD9Npq4oo8dkV5C0ACjxU=
  - secure: Dx9kDWMtZI7z2FVBFuF5WXleOrxfxlgyyZYiMELTWNCk6B8I6WZEV3fdIbVMgutPBA6o0JN1pLGeq0u0oMODpTvN7uAaNY0CxHZ78im9qtCE3MHG9k75nCi7VC2WCj8rAGjbCTCY0ar0f3gih2D7a93IDuDCPATz9dYpWPam5oeWKEkDuwYKa4qoH2X0XDnFm2CcL1oaZ7TYFUge6Ina1T+IoLu0+suUe9Gshe0CY8QQb+Byk2c8ZDQinVZKftcsQKE3wJkv9jdf9MXSxiJ3Tkm7qT0pbGdOJc20JDN4j6OQhyiZykikNhFJe7GdQyTpPC5dvq7yVbTTFPVufSe7V6VAvVMD2ewbcg/JlvUdNPr4XqF18z009UyFsYABIdZDJn9oDNEQqHNPTaM1DSBnjPCRhhYVGz7EelvridPifAxBOb24XCVeDJagMYPzuSxnIv5Iuj5C2U1pNihgvf9SHu+5wnYjxGOsmpVqZ8etgrIIo46JrM6bXm5dB7ZYUoLCu+2hSEAph2qT4SynPIa1jZgcUTHbkdJBC5VCX2Pp7E7unBD13uywUb6jhDPQdpzLc/mMtbAHPgnOnYItC1jGX5mCLaqPL/8MgHN35KvWJbIzqzmWDE5GrQPF+5H2LcVM4asT73egFEkNnfOM+UJQ+zWcKgjo81wfi78AqCpu/54=
  - secure: aSBRDMZl+SkKunTTwTS8hRVqKWdz6DiWnna6M7G1A5j1oEkOhnF6veWNMHeFTgvk6MvW6c0wD50+y4dfpLiuWuvIhoVV3VVuKAGinE0y3q7GAnYeub4ieMWbpAX9s6DYQKr2t+Uwcs8U2MW9albEaAbg95Qq8M8+ERAdhkeYrQ0JZjgX4lnmO6BvUg7Tg59eOLEBE/wLTv0zd5EiWUpHXu8y8MIiVaQ/qI5reEYAm1UhmyHlhzydDIoBMKnkZ+8re5dUcGhbb8EhJjYuHQQJB6gNHn2gGACcor7rxZwpF6ZICUrFI3QDTKLPVKsfvDq35qVE20OqDJD/u+b3Ozhjoagcwa3Z59kq/byaVb0j113r+jK4agn0fqiBjjUsG+7AbdHHkmNdm6UaT/HwceDYVnUOfek6dTnrOhpmOVpaTqa05us7a4f+EEujA2YEp4ewHkjcsYbgjr/Lq7TkFEkyb7uFJCPpm9s6IuPUTYqv6GmK644yq/v487REAJ86Sidh2ekLtrPZIcZeXp051XgL7ZKciohn2xjmW5Kqg3wxUjvcd0Qcuu7PVfSl8KGlPHrSc9OOcOx4CKZpYG/swDrIvFrFt5L9w3bFTAxsbiyMr4nBRDKqaQgEYj8AHFJqkMc9EuBaoKNE+vpuzBbZ+DvqOtx3moIjcpPuIC9PFVscmOA=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: VXMDIv3nE9n+uNUex0UDNrodrE9SinQ1A/+fVUQFI7B6P/1FwgMv1lbgHXuWiG7JGPHPzrlUjLoY1EV/sBzmFp9SUze+lmzm1JUTAtRN0+YsXGH51/gaWVfmJT522+FxO20mEwvj17fn0nYBgRkZoTCvEnSS5wGRfn/exKcaurQVVTvhe3LzxPZQ0SAz3TOFOKWe86gaM3/ixmiYwBBaepF4EbriZ3KUePZ5ToYQb96JRW+bJegw+0/rrD8SUYJeeWbHbeAHDO0RRV3rCgm+hs2QUo1Hc0HDDM74Sefi9UPQgWES2zo/nE+Cix+RDX3rGrLvzwaOl4PZXq5Xm5iuYdFmOfPx9HehNG6UjvDHUKWA1L+EX/oqYpdRefv5R7JaXGfGVcT3/r1TV+DZdgA9UInuQ82/UobOj43wS+tr4naeuYm3IXDNS7Me2o6i0jkIkgbyvV0+DfB/mKR0sy0yhSTCqcP+UM7XgpuqJeb5oEg6pkjp9FbnshnY92RAMQaDzpk3Mgeq9BU0i9ssi9fhQSiws15f8+i/4rKyGUYwqJ2Q0N5FcstMgnt+oxQJJ0zoX9vv4cC/0zXMHz18iK2Ocg018H1tgRRKnfT2R1FI3TvBLg6GY0VF0nyyUQRDIrTao/wpqqOWuct1kunuRRIEYijIkd2oQsCXhLgz6ThAYoU=
notifications:
  slack:
    secure: pHiTrQtTITBeVv22C2JojW4Vgps72R1/WKGYSjCMuo7r8eUyRSi0DmnrybIUygkyrzrNvxk9f6KrYoNXpfa+c9tHSKtSNr7MyCRlI577Fz5w4Q8ypKJxDVkesAVJuiJmTISMFF22ceIIv6p+Ic6S7fRbEVYH9ek5AKDawj5GiqgRmv3XxK24/8ubsEaFjoJ+IBx1JWXq1hW7GNt6ho07qgPm4AOGYXwJuvxPmHeQ+z1M+67ltUmwx/oM46gbAOMZPpcW/iDWE/zULIlO9G/r7HHs1ZfInc+W3nROpelUEly5Ef9aCZo30pDUofbBMc02nBjlCpVdHy7yCa/9m96H7uJaQ+Xt2A3FqEgfS7R79OR5xaXQWA38dOztIo6+h4lb98lTREzct0RpG9QZRgo5F7MrPlQiUcbvhRDCr30AXGmPdrg4F98iQrCBqGf5TFNWWKhuAbXc3rpDvODAmc/xxCyIAlyhAXGl2EkSb45mQGfSb1g6qEtK4gtYDXYzo6KglVhaTZVStkRnz5Hi3nVyuFyL7UEoRmrTBBtzZa2fuk1JI4YRTrbzcYdsvTsaAflUiAvLijSCqijrJJ455Wufu7bDBMdgU9pIf/5KRx2TAEovAZywsAHzuEwn2sOoUVNKzqSkBdd/S0CX2AorqWbehcDhG2N3zTnvy/aA9xVm7YU=
