language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.1
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_Common
  - secure: Lv1KKU8JfSicAU3nVPjKP4HAQ+c6WE7hIcso4Uy2NsA49Bd0Q5DJ6IgdGB0JIl4H57ufbY3cFNsTv2sbpcZXuHHLE+W7m5YsSxpfYmsu1KbnA20tvYS9aiODfb0Q6drlX7zCPE6LzxL7vEi6SaxgKhiPDcj3wognFOj7dktETTh5oZs/UMvVDpPp5kwUSmdLc9HqksDBkvkjozYmSa6r13iHet8v3L2+qjITvRG7x1yRuTRFo0hAfYbTYfsmVi+9IuXU8KU2TI76qneSSYXeMlfx+VkBqCFEyOfh41XFY/2hgo3c+5LZA6q3bX+wxOisNHk1ztcVLs1CUp/VEzG194DbMjPrIfQT3evIVrJ7gIP9Z15XYCnq8Thdt3AKNFvi1/cy9n5DG+w5es3ZVQh+zhaoskApw7Ss3h9J+GohRASCrSFHxyBgRdC662NjJd4HLyiBeFSXI3y+wgIVSVh/GmZLZaMuCy68SG9J/kG95xUENzaWQjbBrcLqIEwn7DJ5OeDolmd2tUOQXxwSu10cJx7IiAM16wA0789hYf24MtdXzb3OYLFn6vDqEawH2DXgA8qxA5FgNjUXVGPJi0dzpagacgR1IV0+pJfDfwvHw64FnCtwVc1tEeeVbdiS5miAQeKTJg5TV9HXCrfvODCy7QJJsPjEsydDJmsvrdl8eUo=
  - secure: gvsxAq5eBRQ3jo41sio5BDF/6EzpPmzgPOYEceHqDRP4sb6GSFYMaqeq8FRQ3PKWkOj/8EcnFxRierZfjKSFJt9yFtPq5JqXikbuJ8m4qDSb6DDLLdn8MibD+p9YsKMaDqowb1mASDX+rKjsNK7Y/55hO6ImeGbcTbXIRniKSG4ySS+ugLOu7nSdsEdRnc2LnI5Wdy+XZRN79r76hmlHqm3hucVilov6CWXeaaS0k1yWMniBa8SCGgnnR4oIVGKAdOWokc5hh4uhiDfLtXF2PKIz5GhqmMORJ+cK9mlp+AoBWsW3lTqBGOsbQiQThbRjUZpCpMi+u2OYbLw58t4muYxoHleoS3wEUXu9gCPAjBtJnLZNn22xMtCCv42uezG5MRUJYw7T/xLTMSLN89guiglpywmqFk9hVHXnRia6eUeWcgL0k4JV+tFzcxD6ISDUHQOnOODS87/eBEYR6yLYVbaE+gE0E3otGW/dk2xy2Fu91pTDOgEeKhg2uoqJQO/WYiVonmV/rHUiJp8ymgxbTYLTAYqkuxuyDqrUvXI6o0PJsWhlCTD5MYcBQ7YrG7wiyGQE1X77P7Xu+q2CrcjOIM8KXIS33iOP1L/9E5rKRl8ojyBNilufvzaxNaTCxFw0gvDbYfmTo2Rd61A8uDdb+SLLXTJJa4g9iUhmTHSmZp0=
  - secure: JBbjGsqTxKtquk2QpDoXALrnd+wRtHo7zAXVom7SPgYSlRaIUNnQlMHGj8sp8swDjUaeHNc2ozxLLpS5FKOIi1+4jujiBKCrVowFu7AYLVgiXxgG2eOT1tKaIADH1HGlFfAJ6h11/5cOBrrKeWU/TKCrdOWpJEsd9h/X5+WAFN6I0ShZdz+gs02cFFCybZuklnbWMiEUbkDayWM5MmUYpBh5OUmU8QYjh9udhVvkLOFOkU6BNut5jnO9CBLnFbsYKLXLOjV3F9tYHRYTlmq5cAg67Pb3mqyaIKjG7YStHB+P7RkCVFnp23E0GCOzU0cLIYqO94vImkJPhRIm/ja2DXXGnnmMtYvsp7vJPJNrC1TJX6WlUNQlkRc2ZGjYoB1Yfc6Wqpa/Wd38iG8aabOpVyzCFh7jl13E2vl6vYofa/zAwIPKAEcf3GJYTsqdpqxiTDPhvleAvXHd2kW5iF8eHRdN47yIyjSJC2QwGxcQp/519iddVgzxethXz3Vu9fxXHqXN3mWrtrsLNxtHUW9cf9jgSV1r+PFYiLL1Gy4acJBh2Y5FUvq7szQB96gpneKfuggjo0GoiZBFsEDJl4Lp3+iI+IrTRMvnMY8kEnK0AUIENkHfbBLf+Nd8bqpNmX9TULd65yXV7hrT8u6tnxCIiEd/rGJ4DdH1UaHwOijim5A=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.10
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: NL+5wcthN9d71U/inJs/mqcGqBDClLt6OzvmgVrciNQmkGmT5DVLuwkr7Btah/G3zeii9Puj1v+LeJWv7MBmSNngz4oMvThAmsuUGSZKNapTvWOOh+J2gElWycYzsbT9CTfbvtas3K3aNlDUxt/iHIG5MFlmuEgEz/luGaVLeQxewACew1BDY7OJj2BV7h/Mb08CAxZ1ZCaniZ8HA/UWKoRNvPuC+UBTbYu9WNOjZBgtfp6Yparjq8UL+aPDihGSwSMQhjACNzXu90W6Pso/VYxK9azGpj6uXh0GA9LigwUaMDV2LPF3FlcUKzawoNUn0OxUUPj0JdRiivEkwD9zTXOehSJnsTT2MfcvwXlxt3/mla1vHx0xCbHg+V0atzLwvCp2IqN0uv9+X3ty4huM8NXmLMHkeV8wyhoj9iTc7NIbM9vC4RQRffqc84e+qpf7Gqi8okb2T8bXNi1xZqxmfwaCFlxX+MIOsllU1gaw1R5WvH+VVDkux0QPQ/pASsbO6CcCZDoPhBJWyNSNL2CCO86l+kiPAMRFchPHJ+Esp8Ow3V96azj3iysIuCWGXP9sYePAycu8wvu/6BD5gzzhmQX4u1Ct8g2yUEpXTvXSlqvKf/t5WJ9hjo58vWXu9EoVDz3CKs7Pa8lfLutcYKJcK49CWvH1RQ3ro71e428dn5I=
notifications:
  slack:
    secure: dnylFi4bYUVzMW2QPlRzn1w8KrUgzFHmPUwXsaCu136epGOIk2WRcpUBrqbYhe4Hw7iP2XOezLC9dbaRgHf8MCYZK7gs6sXywz1eVMIcrI4M0hWr+M4uaajRp0HXUelctObpw220qg28mVBo4sTOAg7xO3ZNZiS0OK3+ggiPTh1rZMhSgmDahLxnMogVm4q6AidG4DdgCyKB7IrU+0nlNrRrKIjQE6BDheSXaIZGa1FjT4UQ8yTsleY49IN1Fp2AEHScUtdIX3TC3kuI5NY1ihYy+d5m676v9yNiQDlsYFyDAX0R5uOdSZAq+snmrI8ymPgNX40fIrZkKz7W30SOLMwEjiwS69H0gLxwXp8uP98kMBu/W78I6EAkVWl+UV/dBjNvJrhOOsFkIVpk3WuJFx1AeIhPaxnBr/0sZpCu94u9nkksd8HDMY8JeldCKEqEzMhiYs+WCWTwfgfXNlcOMgIOSql19zDMBM4ySM6h72BA7GQgnZJHQ1nc8qb/FBmMoHcVdhOLZLRtnFZXZUeuEe6D7+4XhIqO3IQFWiPiBT3AyxhImpN1jUmnSF34ObaBjrxXJOh4TXxSQ7/o94AehbkSWHPEg48OY3J1njs5N8koLNLliqD6WZWGiBKFiN1wJlGRcvPSH9RqiVBw14tSJzemHJjN7/jYdmkFyGzaGrQ=
