language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.4
  - php: 5.6
  - php: 7.0
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.2.0
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
  global:
  - secure: c2ppAhl4A1pp5sR62ICjN7U6w6arP3wvrD/QK5S7IYi462r2tiyO5SlEli1OQENWcHKcOkykDBFifEOUGfUC/0DPRiLIKaOZhTIensXdyok+JR2PGTpza10tmPZ7Z8nRrW0o96d2eZcFChbVfUODfLsDTSBrZWmoNOJMsbadtFxSBJ0KbPgIcLkYWyEZf2DdXCdOCQcXOgLGQNJIQh/7Zb1PQvpN17n7/2dhGotMDOvGcLn3LeAGhoocv1qUhjhiqtfgd0UWOaLaGyerKm5u3S7IFgZBRxX87hbN0NL63WUV7S6HvaywHXfvu9n4v5vEGsBJGfptwcgOzdMXp44dU0ANy5g4UCQtApZqbARDYwlbKF44rQ24qsqrN1sVwgrJ58sUd3q+vH0aflv9URFtBy9ynNlEOQl6HaJhoPPPr4iZgFg7Nv5NBsvQ+ZbDLCO0NIcybao35a4dv0CIZnAPib6nx/ePOAsfH0kB/u5sTc8Q6KIO6+HuUE7lXMGzjXRmV3v+Ybq1I+zdMYqwQzUTQAm4v2Bhj6/r1BK3gtEU+T+vOtNugS3xicSdIdo7i3Tmq4kYh4Be/XScv/GRnBEKDuw+pX7ASLbEO9JcR/v/gMcNWBNNwA7NYSWk02RFH1e3tZuAYnYV4SvNj5rA5cKDkhAggcaAnywfTgA1tGbKXUk=
  - secure: otW98fy2RB5GaeF7ekmJlrS6R15hKHcK5RKsqD8tQXbPEyoG5gwY2vJOTQusYC/85EW/RQkMzPPZuHiBF8SIh3KJ+GZk1sHchMg+9wRgKeU9PbbZpDBwUJ4LW4y1vwHmMmKEE7iXXRry4eTkHrHEk992tosIMGFWP5i9xWbYn31/d6DQOIdEXhGB1f1iY5umrvDPowY349WELrQ6UIlPBru+z2vaf7SbqK/oqsvgXzZBPmeMoBevWFaYyf1ph4n+RCid4KTttnA+PRMhwhix8GZWsY3z/ysQJHz3OsmnKI6r8FfLsUIm0yGwAp+qbyeflHtFwCwOZO1aRvKH2NOe9UY0zK8E186WYUwpOi9/nEDP3sbRp4JhIR4i76GtRLhu9lrx0qJ+5gLth7Esu0K7bppaWb73IGRQuJu/OAHA1et7n2gCymCPmSAwWSxGYbB+rsViTp1aBvoChC7WDLgEvIZAg/l1QNTLV5Qcx8M3lpXkWXaoxtat2HUir3Dd5+vG/gqCPo0ifjQAq7S6xsV1Kt3giyt54OC2aCxrmuMgtcjnCofuI1URuIBD5l3dL/uFNSrj9GI3aigh8jHNysI2oPJzUBfGr1WyKGcpUcKeBCqr5gooLYc1XSmPtrqDQAEhJWqZqNHIx5G4trMpdXK7uEGIewadG79uTkA3gKMJ8uo=
  - secure: IBp9NtMmOaK3NkoyGs8Cw239SBVSyKtxBmSnUhuDgW3F8319Stso7iNw2uR2cWL4JgkjvrC/LsN9Bu08kjJQUGM5QJrViC//0u9U/JFRWEnus69E6h6jjqo/DcukUjfK3FPHnPGhPS/cXSFuCipts2vxC8oWASnQBCHw/ThD018hrCe0Wf2VOWSHkI/s4Z3r3XdXksZQ+m1QxM8bhj5W0tgY4DknJ9CSEKKyQmFXRmOPoSU4W41d2v+Q2SRfF2XzCKqTmfq81ae/PR4++T/mhuwBEgohxtsfbsHcugT+xOHLip3V9QUJzJTShO/u7fl1SxY9bNF4NYAzkhI8wKaWnYlAzfuwXys68PT1Y3E85D1f1ipB5RIjKq6z9sz3vBm51iB2R0Nm9qZe/gWrkRPo6M1ety69uRFfif3LX9MlMafjWMS5J4PeADQl70/Um7W0PY/6v9vnj0PRNDxavValGqh+tvYTzK+rftmdsWzdHNS4GARKtQpCmz9Xs4xxGEjS6Si8McNnSpFgyPxTkY2UTt847IxTQZnyV34Xs868IY59zDFPZNKFCSVSEH5MQta1pH6gCps7kG6SfSDEHx8pod+qxSBX8jfl0GXU6VvWs9m0DKrnpw3beYPZsDC1+zk7vZ84MWDneZTt3nHDgs2XL0OknxN4ubyRaD6Mu2Qo02k=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
notifications:
  slack:
    secure: VCrX7khHkF11Vg2El39VdqdeWlVrUzgGfujHpNRDMzi4QFU0sfWir0yucfqVcqFkcz00ALOh9WJBNsaeFJprObO/VEbs8Iy3pzwSBUDm/Z/c1zgU7gXBTT4fuviTFgO5lauBvJmn8avArST60ixfB+YV2boJ3+obnvoxceXoub6jJbW8Kv3LdUkXeZ9c+vS0rnGWGFW5x+/VedRguzBdXreCa1gcBYo/ckDmk9JCHvTujEqiRW8ZK5d3AZnciUGVUHpyQp4kdxbsj+7chp1k+NeQ3HISUv/t6rCWn1KtQy09GnuSYFOxBmNDFOlyYpl/9lTyGgjoPa2p4weQCREvqXbbqefMS5ECuRDRJsL6CCvheCIkIwbu/K70MW0sEQFViBQoTyMkYJ9J9U2puhJXdodEYgweo4MzfxWCbzk3jedmNcP3mGJVmWj0COk5FkZUCD4L4k1E8fFqbiyC1qJo7ifE6tpl5oNkHiOCFFY2L69/ho4erDFbPNOwcBWoR4PxOCq52qLc4eAvoDOBnPJ35orGk0AunbL7AaI4itiaaLAlkBE20YSNsCliE72MaFUfdsFah8mxSh1+CHV1yQIO/bYFtpxtrZuvGq0eiLd1o93iotLvDwF3kH68Hjq0lycBB/40427OeDDf6srBeryTq2Cx77KHyLrqK1AL7pu9YWU=
