language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_Common
  - secure: F8/3B/hfmOZX6onokH4HJer1yi2w8o6UvJ7shXwXErBwAeMtsq00+SrcUG5JQD3acQu1q6ZdunfqeZ8iicOC9hDiAbxLGZCdomFYUksCW7uGsFgIOeodl9G6E9jykNisBFC3E3by9Rb3tnGvbBLmX0x1bgJAsq2tNk8DChm0Aj065aw/p/UBUGA8baEXMfpiA5bXNqrESNDbFFRDE4hnd7SsHuAAYsS2tC6QNAzHLI/LrX21tC4DFn9tbbi+gHfLqIa4WKpzqwviTJUPWvYP7MIMsDfp9DO677gRMO446NlqcuBUeEnoNsfLs/5G22qc0LKu3Os6PU8YLOhzqsnaZvP8XAN6v4wVVHpoCL/bNf6b8P9w+DEiCMLI05L9Sfg6/ww30k008m2aiKIK1kCOyKwSbcvGf2sEPjqdmR0ZrFgmhdhMHVDiq6cNHBwdU2z+Hptf9SJjiYuj/Rt4CuCBzoIB/i5HzbsFx9kQuMkzkkWbaHCi0VUZMNeUFddJV58PYJYklYMFrIiwzhFXNySCr1RiA3MOYeUslmr/9q3RjbXAIz+1cAB6UtpPZjy7zBHfjxaDqzhqXwgjBXKdTV/gt7WcYV0KmnSqiuOTZTgrhBT668vf88lIywA8zr3qNmnTj5/GihZp3rm4CD/xy/cDFgawc27Ehcc7Eo939yOdfhY=
  - secure: ReGpyLLRNfK9vy5srt4p6ZRbneofM9EZZa2dPH0QujPDxIr2OLT6I4MiFqEGkwuMurCIG6zS9N8Ryl4d7gTJfENjoabcftU7aWrKlLTiB5zxHcw/kHdbH+ipLGX5Kj9JREmgDwEHVweHOiJGwDrQ76f0b2mBCCuCWju0YT/q6ZOhSdC2IEPaGpY0VrRTA9hBjejwq4XNkxV8OdGHUehZt4ygvhodS+/FbGrNHOw/qoh9EGGdzQtaLl5CHt0fZr4AicBL4tHx8myZxZy4o+MOYImG9+SVfearEVd8ZXBAZ54of0qwE/dDBD5ucIeHb7VHe++fqS2DVJSOjLNsI8SX6+3uCbovn426NP717gncxhbJESCvdf0D2uzMMSneD/vbEmclGlRAdDKoL/qSEme4S4N9350Z9Oer57UKRtek3v1j9+E6fn+hUKUsUzbYuIWSRGKMeHSd4BBc0/+kqDzS3jWKf3rAtY2Xix/Fzm7gbll8C/i0k6iKbLVV05aHOQ01R4GIzWfA4n4w5OC6ZkdIpwPmS15VR+ElHfepRLTHiGGQ1OgzSrZKqKPNMaffDhRWwQNVQA8XRUaAS6tK1GdH3sXLFhrOSQkOvj6DP+ujhlZq5AqO1vogDhUPEpc52+DJkTcQ3C/TTVjFSHhfqk0k7GRJCTVlqH7OtYiORFzamsI=
  - secure: cF3wEZ6741j/ytnPHHkYioUSCNQ/XLYSWcZi5yWv7Je6Pa00g0z8i3e52toCCq9SWjsC8C0o9N7F9q2ifnFHLgtIILECE8dtJ1tzAIyLDBXY7kNVMF0kRDAI94FUC+mzaXsiQT8HNwB448JMIMiks5RGaIQ3j5v56Dcxx9Pi+Eaq15quqS5TdH71W00knGMkFAm82PUgQODh4Zk5CDhAyv6wybWhBtTSo5x8nRLZasRaoRkPFBGIjXnMaan6up/m1Sf3SN3JcDnSGgP6mnbubNTsHDuHZUbrrBmt6z8EU+Peo5d1CZCtCyrEta8XsQ7VtpAbQJiDR6GNdtx6VFVYJseeMNczwZ2ZJQABLY/6oIldfaodX21OeIkg3R7/sveIw2aR8RKDKKhmgmC7/SNS1KvfQwFjaGh6fLr2PvsQmAQk2ohYeQejV3J+kSGfG61qmfudeVemgeYfEXwe1Gk+N3Z8He0s251xI1K3u/WN6nM2X3Y08x4rW3Yxz7L4ajqhrmqyFRffk9FOix8XX+NhU76Hwkv0BuMxmYsj9meeJYJbffjqqfMM/xQHh6cQixUMff6si2B/YnRuaUExMI58tk679I0KIhYXq839q7RpBJKLxBQCWjVuuILc/y2+bPZxSo+NfCSnuSiN+rdrT+gerFEwjgAOU2/8I9W+tUPkY0I=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.10
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: ZR7YejbfO2HEll1WAA/eRCtkvh9fSpwNw9+d05ySpjNSm48bRqjoXb4Dd4sv5X5Z0twMUmpuowDSKCXTrduoqqD59oc9S6w8KQd6Qlt1N5Tw61l9CMN1IHDDDGuNudVHwkvYbzcMCFAK0l3Ccmi2EuIxbztnV7wNXFIf2c1KX1zjydJ+/zBX94oYkvvcwMkl2g/OgsvB7/Qh0KStye2DejaHcyBUrtfe0B08Q9LKtA0D5U2iF/gjSlu6i6C7LD7HkJqeco9xA41zlu3e0xIuatRw4itC93DEiX3iJvoRnQnsQ4FYCDaJGTxvLY/e6hlw76zQFzWQcrockFefZWgoRDbwUdKICzt1dCqlh77dqR8d+h+A4rzB1Wc5SZvWhxGet3LXN9/LgyG8tppvanb/Ld623b94aAEtA5gtFcb5X7WrsN7oYiyYewl0VR9C/pZHgCGge8jjd6Oak/BvaVMTEwthoRL6y5MDenq0CZUHRaKp/XiTMK8Jmwsd90MKQ7Do28qy6kYeZWNpjX3mr9zGJU5Vo+ojA23Kzj6ri+yRRHQ+FjkdisbTJl+2442RLMYh6MD/qdr0tQwTiMOFvYHqNtc6eVNab8Z7faz1FCYKu5i8GADSWUxE8rn8vu/4KexL2KgpguU+sOb8/ZMN2RNRJaw1dNyu4RZfmYCU6NZ4w7I=
notifications:
  slack:
    secure: T4ruZKJTKnOPpA3OI944zr8b9DBEdg91+mUh+NxZi1GTsvCrBppqnFydN+gV1SIR/YYCC6x586RRvHhPJxCV3lLntOUSf+fl9R3233N2DnQfZ8sqUXrs2ttF62H/iBQfDlJjqCz/zbIIMBHQ8R90lA3f2zOMvZj94jbLvi6dm4Q8TKyPEDZIGg7L4wVo9yDSxfF8h0X60L+y3caeMixnRCeQ17DNIRB2ZdCSnSoBDNYnS6nz5AKhdCjV/InP3g85EAMCuLV+Gar4SmidlOteoVd64WImn+LoJX6VXwAlWpz4AE7Pjc3LuFIMnWsACetkPTFjBNOEZT6/p69CePT0WX1vV41fVRH4c8ncadZ6CB6LFR9VCUOOxn0Qvwyrh+Rwe+O1xVrytUBy0rRYKYwqbWV+oYkbHxdBQDwOCZGSOq0WptbtsA5ZhAO5kZP3pRcl1EKYsamH3uR9Ykyk2Xh+NT3EwNFtf3CRpO8s75mplnB2pSflE2Q9Oh2o/H4vnW173c8wsPZmZLFSWj8pk3imilRSBJoRdQckaXZwNek5sLrIOP3HNkSMzPSbIIRYnNdQOCIygCQfiTxmutFbhSvwgXMMwB8iEkc/wKjBvcLy2QXoJrjjIG29TlzFz0Y6QDGKpZFFoDLC7MkY9FmfHPfGIlfNVEfTgI7RDldwJtTXgNE=
