<?php
/**
 * Ffuenf_Common extension.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category   Ffuenf
 *
 * @author     Achim Rosenhagen <a.rosenhagen@ffuenf.de>
 * @copyright  Copyright (c) 2018 ffuenf (http://www.ffuenf.de)
 * @license    http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('System Log details'); ?></h4>
    </div>
    <div class="box">
        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label><?php echo $this->__('Date'); ?></label></td>
                    <td class="value"><strong><?php echo $this->htmlEscape($this->getTimestamp()); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Class'); ?></label></td>
                    <td class="value"><?php echo $this->htmlEscape($this->getClass()); ?></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Origin'); ?></label></td>
                    <td class="value"><?php echo $this->htmlEscape($this->getOrigin()); ?></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Level'); ?></label></td>
                    <td class="value"><?php echo $this->getLogLevelHtml($this->getLevel()); ?></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Message'); ?></label></td>
                    <td class="value"><?php echo $this->htmlEscape($this->getMessage()); ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <?php if ($this->getDetails() != ''): ?>
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Details'); ?></h4>
    </div>
    <div class="box box-code">
        <pre><code class="language-php-extras"><?php echo $this->htmlEscape($this->getDetails()); ?></code></pre>
    </div>
    <?php endif; ?>
</div>