<?php
/**
 * Ffuenf_Common extension.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category   Ffuenf
 *
 * @author     Achim Rosenhagen <a.rosenhagen@ffuenf.de>
 * @copyright  Copyright (c) 2016 ffuenf (http://www.ffuenf.de)
 * @license    http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<div class="grid">
    <div class="hor-scroll">
        <table cellspacing="0" class="data simple-sysinfo-section" id="<?php echo $this->getSectionId(); ?>">
            <colgroup>
                <?php if ($this->showKeys()): ?>
                    <col width="250">
                <?php endif; ?>
                <col />
            </colgroup>
            <tbody>
                <?php foreach ($this->getSysinfoData() as $key => $value): ?>
                    <?php if (is_array($value)): ?>
                        <?php $i = 0; foreach ($value as $subvalue): ?>
                            <tr>
                                <?php if ($i == 0 && $this->showKeys()): ?>
                                    <td rowspan="<?php echo count($value); ?>" class="a-right"><strong><?php echo $key; ?></strong></td>
                                <?php endif; ?>
                                <td class="a-left data-cell"><?php echo $this->formatOutput($subvalue); ?></td>
                            </tr>
                        <?php $i++; endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <?php if ($this->showKeys()): ?>
                                <td class="a-right"><strong><?php echo $key; ?></strong></td>
                            <?php endif; ?>
                            <td class="a-left data-cell"><?php echo $this->formatOutput($value); ?></td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<script>
//<![CDATA[
    document.observe('dom:loaded', function() {
        decorateTable('<?php echo $this->getSectionId(); ?>');
        var tableCells = $$('#<?php echo $this->getSectionId(); ?> td.data-cell');
        if (tableCells.length) {
            tableCells.each(function(cell) {
                if (cell.innerHTML.toLowerCase() == 'no' || cell.innerHTML.toLowerCase() == 'inactive' || cell.innerHTML.toLowerCase() == 'invalid') {
                    cell.update('<span class="failed" title="' + cell.innerHTML + '">' + cell.innerHTML + '</span>');
                } else if (cell.innerHTML.toLowerCase() == 'yes' || cell.innerHTML.toLowerCase() == 'ok') {
                    cell.update('<span class="passed" title="' + cell.innerHTML + '">' + cell.innerHTML + '</span>');
                }
            });
        }
    });
//]]>
</script>
